### PR TITLE
Add a `getMany` function to ModelDB

### PR DESCRIPTION
**Pull request by rjwebb**
Implements https://github.com/canvasxyz/canvas/issues/347

This PR adds a new `getMany` function to `AbstractModelDB`. This lets us look up rows with an array of primary keys, instead of just one at a time.

In Postgres we can use the `ANY($1)` operator. In the Sqlite we construct a where clause like `IF id = :p0 OR id = :p1 OR id = :p2`, which unfortunately means we can't use prepared statements. In IndexedDB it's just a wrapper around individual `get` calls (maybe we could use a range that spans the set of keys being looked up and then scan them?).

To do:
- [x] Postgres implementation
- [x] Sqlite native implementation
- [x] Sqlite wasm implementation
- [x] IndexedDB implementation
- [x] Durable Objects implementation
- [x] Write new tests for `getMany`

## How has this been tested?

- [ ] CI tests pass
- [ ] Tested with example-chat (including login, all signers, and exchanging messages)
- [ ] Tested with `@canvas-js/test-network`: (optional)

## Does this contain any breaking changes to external interfaces?

- [ ] Contract interfaces
- [ ] Core interface
- [ ] CLI
- [ ] Data storage formats, including IndexedDB, SQLite, or filesystem storage (will this break existing apps?)

### CODE REVIEW

**Comment by joeltg** [comment]
for sqlite, I'd guess that cost of re-running the regular `SELECT * WHERE ${key} = :key` query (that we already prepare once) once for each of the keys in `getMany` will be way, *way* lower than the cost of preparing a new query with a separate `OR` expression for each of the keys

**Comment by rjwebb** [comment]
tried being rigorous with this one, it doesn't seem to make much difference

https://github.com/rjwebb/sqlite-many-get-test

**Comment by rjwebb** [comment]
I'd be down to just use separate queries because it feels simpler though

**Comment by rjwebb** [comment]
Updated for durable objects @raykyri

**Comment by raykyri** [comment]
Looks good to me.

**Comment by raykyri** [comment]
We should consider replacing `OR` with separate queries in the sqlite implementations also

**Pull request merged**
