### PR TITLE
generic result values

### PR DESCRIPTION
**Pull request by joeltg**
## How has this been tested?

- [ ] CI tests pass
- [ ] Tested with example-chat (including login, all signers, and exchanging messages)
- [ ] Tested with `@canvas-js/test-network`: (optional)

## Does this contain any breaking changes to external interfaces?

- [ ] Contract interfaces
- [ ] Core interface
- [ ] CLI
- [ ] Data storage formats, including IndexedDB, SQLite, or filesystem storage (will this break existing apps?)

### CODE REVIEW

**Comment by raykyri** [comment]
I've tried to set up an Actions<> type by pulling out the actions field of `Contract` inside types.ts:

```
export const models = { ... } satisfies ModelSchema
export const actions = { ... } satisfies Actions<typeof models>
```

This seems cleaner than the syntax right now:

```
export const models = { ... } satisfies ModelSchema
export const contract = {
  models,
  actions: { ... },
} satisfies Contract<typeof models>
```

At least we can have:

```
export const models = { ... } satisfies ModelSchema
export const actions = { ... } satisfies Actions<typeof models>
export const contract = { models, actions } satisfies Contract<typeof models>
```

But for some reason the Actions type doesn't get derived correctly. This might be a caching issue on my side.

**Comment by joeltg** [comment]
yeah, for that you would have to say `Contract<typeof models, typeof actions>`

**Comment by joeltg** [comment]
ie this works for examples/chat/src/contract.ts:

```ts
import type { ActionImpls, Contract, ModelSchema } from "@canvas-js/core"

const models = {
	message: {
		id: "primary",
		address: "string",
		content: "string",
		timestamp: "integer",
		$indexes: ["address", "timestamp"],
	},
} satisfies ModelSchema

const actions = {
	async createMessage(db, { content }, { id, address, timestamp }) {
		await db.set("message", { id, address, content, timestamp })
		return 9
	},
} satisfies ActionImpls<typeof models>

export const contract = {
	models,
	actions,
} satisfies Contract<typeof models, typeof actions>
```

... alternatively you could just

```ts
export const contract = { models, actions }
```

... since `models` and `actions` both have `satisfies` assertions already

**Comment by raykyri** [comment]
It turned out I was exporting the wrong actions object, got confused since ActionImpls changed when IPLD was removed. This is probably fine to merge now

**Pull request merged**
